config/routes.rb
RichardProject::Application.routes.draw do
  devise_for :users, :path => 'auth', :controllers => {
    :registrations => "registrations",
    :sessions => "sessions"
  }
  devise_scope :user do
    get 'company_info', to: "registrations#company_info", as: "company_info"
  end
  root to: "welcome#index"

  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, User, :company_id => user.company_id
    else
      can :read, Company, :id => user.company_id
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users, :dependent => :destroy
  validates_presence_of :name
  validates_presence_of :subdomain
  validates_uniqueness_of :subdomain
  before_save :standardize_subdomain

  private
  def standardize_subdomain
    self.subdomain.downcase.strip! if self.subdomain
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  belongs_to :company
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password_confirmation
  validates_uniqueness_of :email, scope: :company_id
  validates_presence_of :email, :username
  validates_uniqueness_of :username, scope: :company_id

  attr_accessor :subdomain

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    username = conditions[:username]
    subdomain = conditions[:subdomain]

    if username && subdomain
      self.joins(:company).where(:username => username,
        "companies.subdomain" => subdomain).readonly(false).first
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :check_subdomain

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    if request.format.json?
      render :json => {success: false}, :status => 403
    else
      redirect_to root_url
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.admin?
      users_url(:subdomain => resource_or_scope.company.subdomain)
    else
      root_url(:subdomain => resource_or_scope.company.subdomain)
    end
  end

  protected
  def check_subdomain
    return if Rails.env.test?
    if request.subdomain == 'www'
      redirect_to root_url(:subdomain => '')
    else
      #Redirect to subdomain only if user signed in and is on different subdomain
      if user_signed_in? && current_user.company.subdomain != request.subdomain
        redirect_to after_sign_in_path_for(current_user)
      elsif !user_signed_in? && !request.subdomain.blank?
        redirect_to new_user_session_url
      end
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  #POST /auth
  def create
    @company = Company.new(company_params)
    params[:user].delete :company

    resource = build_resource(user_params)
    resource.company = @company
    resource.admin = true
    begin
      ActiveRecord::Base.transaction do
        @company.save!
        resource.save!
      end

      sign_in resource, by_pass: true
      redirect_to root_path
    rescue
      unless @company.errors.empty?
        @company.errors.each do |attr, error|
          resource.errors.add(attr, error)
        end
      end
      respond_with(resource)
    end
  end

  #GET /company_info
  def company_info
  end

  private
  def company_params
    params[:user].require(:company).permit(:name, :subdomain)
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  skip_before_filter :check_subdomain
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_account

  #GET /users
  def index
    @page = params[:page] || 1
    @per_page = params[:per_page] || 20
    @users = @company.users.where("id NOT IN(?)", current_user.id)
      .paginate(page: @page, per_page: @per_page)
  end

  #GET /users/new
  def new
    @user = @company.users.new
  end

  #POST /users
  def create
    @user = @company.users.new(user_params)
    if @user.save
      redirect_to users_path
    else
      flash[:alert] = @user.errors.full_messages
      render "new"
    end
  end

  #GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
    authorize! :update, @user
  end

  #PUT /users/:id
  def update
    @user = User.find(params[:id])
    authorize! :update, @user
    if @user.update_attributes(user_params)
      flash[:notice] = t(".update_success")
      redirect_to users_path
    else
      render "edit"
    end
  end

  #DELETE /users/:id
  def destroy
    @user = User.find(params[:id])

    authorize! :delete, @user
    if @user.destroy
      flash[:notice] = t(".destroy_success")
    else
      flash[:alert] = t(".destroy_failure")
    end
    redirect_to users_path
  end

  private
  def load_account
    #make sure that only admin can manage users
    authorize! :manage, User
    @company = current_user.company
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #GET /
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RichardProject" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url(:subdomain => '') %>">RichardProject</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% unless user_signed_in? %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_url(:subdomain => '') %></li>
              <% else %>
                <% if can? :manage, User %>
                  <li><%= link_to "User Management", users_path %>
                <% end %>
                <li><%= link_to "Company Info", company_info_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <hr />
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, :autofocus => true %>
  </div>

  <div><%= f.label :email %>
  <%= f.email_field :email %></div>

  <% if @user.new_record? %>
    <div><%= f.label :password %>
    <%= f.password_field :password %></div>

    <div><%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %></div>
  <% end %>
  <div>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= f.button "Cancel", type: "button", class: "btn", onclick: "window.location='#{users_path}'" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render("form") %>

app/views/users/index.html.erb
<%= link_to t('.new'), new_user_path, class: "btn btn-primary" %>
<hr />
<table class="table table-hover">
  <thead>
    <th><%= t(".username") %></th>
    <th><%= t(".email") %></th>
    <th><%= t(".created_at") %></th>
    <th><%= t(".action") %></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, edit_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to t(".edit"), edit_user_path(user), class: "btn btn-mini" %>
          <%= link_to t(".delete"), user_path(user), confirm: t(".delete_confirm"), method: :delete, class: "btn btn-danger btn-mini" %>
        </td>
      </tr>
    <% end %>

    <% if @users.empty? %>
      <tr>
        <td colspan='4'><%= t('.no_user') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate(@users) %>

app/views/users/new.html.erb
<%= render("form") %>

app/views/welcome/index.html.erb
This is home page